import { OAuthStore, StoredTokens } from './oauth_store.js';

/**
 * The MCP SDK's OAuth provider, backed by IRIS's token store.
 *
 * The SDK drives the protocol — discovery, PKCE, refresh, the 401 dance. What
 * it delegates is where secrets live and how a person is sent to the consent
 * screen, which is exactly the part that has to be decided per application.
 *
 * IRIS is a server with no browser of its own, so `redirectToAuthorization`
 * cannot open anything. It records the URL and lets an endpoint hand it to
 * whoever asked. That is not a workaround — a background service silently
 * opening a consent screen would be worse.
 */

export interface IrisOAuthOptions {
  serverId: string;
  clientId: string;
  clientSecret?: string;
  redirectUri: string;
  scopes: string[];
  /**
   * Extra query parameters for the authorization request.
   *
   * Exists for Google's two non-standard ones. Without `access_type=offline`
   * Google issues no refresh token at all, so the credential dies in an hour
   * and the person is sent back to a consent screen — and a permission prompt
   * that appears hourly is one people learn to click through without reading,
   * which is a worse security outcome than the long-lived token it was
   * avoiding. `prompt=consent` is needed alongside it because Google returns a
   * refresh token only on a fresh grant, and this account has already granted.
   */
  authorizationParams?: Record<string, string>;
  store: OAuthStore;
  onEvent?: (event: { type: string; detail?: Record<string, any> }) => void;
}

export class IrisOAuthProvider {
  /** Set when the SDK asks for authorization; read by the endpoint. */
  private pendingAuthorizationUrl: URL | null = null;
  private pendingVerifier: string | null = null;
  private currentState: string | null = null;
  /**
   * The verifier for the flow currently being exchanged.
   *
   * Separate from `pendingVerifier` because the two have different lifetimes.
   * `auth()` invalidates and retries once when an exchange fails, and its
   * invalidation clears the verifier — which for an authorization-code
   * exchange can never help: the verifier has to match the challenge that was
   * put in the URL the user already consented to, so a retry without it cannot
   * succeed, and the PKCE error it raises replaces whatever the server
   * actually objected to. Keeping it here means the retry runs with the right
   * verifier and the original error is the one that surfaces.
   *
   * Cleared by `beginNewFlow`, because a genuinely new authorization must
   * never reuse an old flow's verifier.
   */
  private exchangeVerifier: string | null = null;

  constructor(private options: IrisOAuthOptions) {}

  get redirectUrl(): string {
    return this.options.redirectUri;
  }

  get clientMetadata() {
    return {
      client_name: 'IRIS',
      redirect_uris: [this.options.redirectUri],
      grant_types: ['authorization_code', 'refresh_token'],
      response_types: ['code'],
      token_endpoint_auth_method: this.options.clientSecret
        ? 'client_secret_post'
        : 'none',
      scope: this.options.scopes.join(' '),
    };
  }

  clientInformation() {
    return {
      client_id: this.options.clientId,
      ...(this.options.clientSecret ? { client_secret: this.options.clientSecret } : {}),
    };
  }

  /**
   * The CSRF state.
   *
   * Generated by opening a flow row, so the value that goes out is the same
   * value that can be claimed back — a state nobody recorded is a callback
   * nobody asked for.
   */
  state(): string {
    if (!this.currentState) {
      this.currentState = this.options.store.beginFlow(
        this.options.serverId,
        this.pendingVerifier ?? ''
      );
    }
    return this.currentState;
  }

  tokens(): StoredTokens | undefined {
    return this.options.store.getTokens(this.options.serverId);
  }

  saveTokens(tokens: StoredTokens): void {
    this.options.store.saveTokens(this.options.serverId, tokens);
    this.options.onEvent?.({
      type: 'oauth.tokens_saved',
      detail: {
        server: this.options.serverId,
        // Whether a refresh token arrived decides whether this survives an
        // hour. Worth recording; the token itself never is.
        hasRefreshToken: Boolean(tokens.refresh_token),
        scope: tokens.scope ?? null,
      },
    });
  }

  saveCodeVerifier(codeVerifier: string): void {
    this.pendingVerifier = codeVerifier;
    this.exchangeVerifier = codeVerifier;
    // Attached to the state already issued, never rotated. The SDK may call
    // this after building the authorization URL, and changing the state at
    // that point guarantees the callback cannot be matched.
    if (this.currentState) {
      this.options.store.setFlowVerifier(this.currentState, codeVerifier);
    }
  }

  /**
   * Discards any half-finished flow so a new authorization starts clean.
   *
   * Without this the provider reuses the state from a previous attempt, and an
   * abandoned attempt quietly poisons the next one.
   */
  beginNewFlow(): void {
    if (this.currentState) this.options.store.claimFlow(this.currentState);
    this.currentState = null;
    this.pendingVerifier = null;
    this.exchangeVerifier = null;
    this.pendingAuthorizationUrl = null;
  }

  codeVerifier(): string {
    const verifier = this.pendingVerifier ?? this.exchangeVerifier;
    if (!verifier) throw new Error('PKCE verifier がありません。認可を開始してください。');
    return verifier;
  }

  /**
   * Records where the user has to go, rather than going there.
   *
   * A resident service has no browser, and one that could open a consent
   * screen unprompted would be a worse thing to own than one that cannot.
   */
  redirectToAuthorization(authorizationUrl: URL): void {
    // Applied here rather than passed through `auth()`, which has no parameter
    // for provider-specific extras.
    for (const [key, value] of Object.entries(this.options.authorizationParams ?? {})) {
      authorizationUrl.searchParams.set(key, value);
    }
    this.pendingAuthorizationUrl = authorizationUrl;
    this.options.onEvent?.({
      type: 'oauth.authorization_required',
      detail: { server: this.options.serverId, host: authorizationUrl.host },
    });
  }

  /** The URL an endpoint should hand to the person, once. */
  takeAuthorizationUrl(): URL | null {
    const url = this.pendingAuthorizationUrl;
    this.pendingAuthorizationUrl = null;
    return url;
  }

  invalidateCredentials(scope: 'all' | 'client' | 'tokens' | 'verifier' | 'discovery'): void {
    if (scope === 'all' || scope === 'tokens') this.options.store.revoke(this.options.serverId);
    if (scope === 'all' || scope === 'verifier') {
      this.pendingVerifier = null;
      if (this.currentState) this.options.store.claimFlow(this.currentState);
      this.currentState = null;
    }
    this.options.onEvent?.({ type: 'oauth.invalidated', detail: { server: this.options.serverId, scope } });
  }
}

/**
 * Scopes Google's MCP servers document.
 *
 * Read-only wherever a read-only variant exists. `gmail.compose` is
 * deliberately absent: composing is an outbound capability, and IRIS's own
 * rules already forbid an inferred run from reaching one. Asking for it
 * anyway would put the capability behind a consent screen the user clicks
 * once, rather than behind the approval boundary that was built for it.
 */
export const GOOGLE_MCP_SCOPES: Record<string, string[]> = {
  /**
   * The narrow readonly pair, which is what the server itself says it takes.
   *
   * These were widened to `calendar.readonly` on the theory that Google's
   * Calendar MCP server wanted something broader, because every `tools/call`
   * came back "The caller does not have permission". Widening changed nothing:
   * the same error, with the same tools. Reading the server's own
   * `oauth-protected-resource` metadata afterwards showed both of these listed
   * in `scopes_supported` — so the narrow pair was never the problem, and the
   * broader grant bought exactly nothing. Reverted, because a permission kept
   * "just in case" is a permission nobody can justify later.
   *
   * What is established, and what is not:
   *
   *   The credential works. The same token reads the calendar list and events
   *   through the ordinary Calendar REST API, 200 both times.
   *
   *   The Calendar MCP API is enabled on the project — the earlier "has not
   *   been used in project" error is gone.
   *
   *   An explicit `x-goog-user-project` quota project does not help.
   *
   *   `tools/list` needs no authorization, so a connection reporting
   *   "connected, 9 tools" says nothing about whether the credential works.
   *   Only a `tools/call` does. A verification that checked for bytes rather
   *   than for `isError` reported success on this exact failure.
   *
   * The remaining candidate is Google-side: this OAuth client is External and
   * in Testing, and the MCP endpoint may require a published or verified app.
   * Unconfirmed. Until it is, the REST API is the path that works.
   */
  /*
   * `calendar.events` を足した。**読み取りだけ、という決まりの意図的な例外。**
   *
   * レールから打った一行を予定として登録する機能のため（利用者、2026-09-06）。
   * 上のコメントに「送れるものは、一度押した同意画面の裏ではなく承認の境界の
   * 裏に置く」とある。**その決まりは守る** —— スコープは持つが、書き込みは
   * 一件ずつ承認を通る。同意画面は「できる」を作るだけで、「する」は作らない。
   *
   * 足したのは `calendar.events` の一つだけ。Google のカレンダー MCP が
   * 要求してくる十二個には `.../auth/calendar`（全権）と
   * `.../auth/calendar.acls`（共有設定の変更）が入っている。**予定を一件
   * 作るのに、共有相手を変える権限は要らない。**
   *
   * `calendar.events` は `calendar.events.readonly` を含むので、読み取り側の
   * 一行は消してよい —— が、残してある。**何を読んでいるかが一覧から消える**
   * のは、権限の見通しとしては後退で、重複は害にならない。
   */
  calendar: [
    'https://www.googleapis.com/auth/calendar.calendarlist.readonly',
    'https://www.googleapis.com/auth/calendar.events.readonly',
    'https://www.googleapis.com/auth/calendar.events',
  ],
  gmail: ['https://www.googleapis.com/auth/gmail.readonly'],
  drive: ['https://www.googleapis.com/auth/drive.readonly'],
  sheets: ['https://www.googleapis.com/auth/spreadsheets.readonly'],
};
